const admin = {
  type: "admin",
  admin: true,
  username: "admin",
  password: "admin",
};

const support = {
  type: "support",
  admin: false,
  username: "destek",
  password: "destek",
};

const users = [
  {
    id: 1,
    isUser: false,
    fullName: "Henderson Upward",
    operationNumber: "542",
  },
  {
    id: 2,
    isUser: true,
    fullName: "Michael MacDowal",
    operationNumber: "657",
  },
  {
    id: 3,
    isUser: false,
    fullName: "Hunter Wathall",
    operationNumber: "706",
  },
  {
    id: 4,
    isUser: false,
    fullName: "Huntington Boswell",
    operationNumber: "721",
  },
  {
    id: 5,
    isUser: true,
    fullName: "Guillermo McCardle",
    operationNumber: "684",
  },
  {
    id: 6,
    isUser: true,
    fullName: "Sella Codner",
    operationNumber: "723",
  },
  {
    id: 7,
    isUser: true,
    fullName: "Chloe Cafe",
    operationNumber: "668",
  },
  {
    id: 8,
    isUser: true,
    fullName: "Sella Boyle",
    operationNumber: "600",
  },
  {
    id: 9,
    isUser: false,
    fullName: "Chloe Cornish",
    operationNumber: "587",
  },
  {
    id: 10,
    isUser: false,
    fullName: "Bailie Halward",
    operationNumber: "796",
  },
  {
    id: 11,
    isUser: true,
    fullName: "Rubina Spata",
    operationNumber: "636",
  },
  {
    id: 12,
    isUser: false,
    fullName: "Dorolice Loache",
    operationNumber: "681",
  },
  {
    id: 13,
    isUser: true,
    fullName: "Donnie Stachini",
    operationNumber: "585",
  },
  {
    id: 14,
    isUser: true,
    fullName: "Richy Moakes",
    operationNumber: "578",
  },
  {
    id: 15,
    isUser: true,
    fullName: "Shelton Roddie",
    operationNumber: "641",
  },
  {
    id: 16,
    isUser: false,
    fullName: "Stefania Hatherell",
    operationNumber: "504",
  },
  {
    id: 17,
    isUser: true,
    fullName: "Christoph Neles",
    operationNumber: "728",
  },
  {
    id: 18,
    isUser: true,
    fullName: "Annora Balcon",
    operationNumber: "727",
  },
  {
    id: 19,
    isUser: true,
    fullName: "Katie Eagell",
    operationNumber: "573",
  },
  {
    id: 20,
    isUser: false,
    fullName: "Marinna Harriott",
    operationNumber: "770",
  },
  {
    id: 21,
    isUser: false,
    fullName: "Darrin Boyle",
    operationNumber: "612",
  },
  {
    id: 22,
    isUser: true,
    fullName: "Itch Swatridge",
    operationNumber: "772",
  },
  {
    id: 23,
    isUser: true,
    fullName: "Sheeree Duquesnay",
    operationNumber: "676",
  },
  {
    id: 24,
    isUser: false,
    fullName: "Ryann Harken",
    operationNumber: "720",
  },
  {
    id: 25,
    isUser: false,
    fullName: "Sullivan Heindrick",
    operationNumber: "560",
  },
  {
    id: 26,
    isUser: true,
    fullName: "Harmony Bonick",
    operationNumber: "694",
  },
  {
    id: 27,
    isUser: true,
    fullName: "Anita Olfert",
    operationNumber: "772",
  },
  {
    id: 28,
    isUser: false,
    fullName: "Stephani Roddie",
    operationNumber: "647",
  },
  {
    id: 29,
    isUser: true,
    fullName: "Erhard Penkman",
    operationNumber: "661",
  },
  {
    id: 30,
    isUser: true,
    fullName: "Dorian Mordy",
    operationNumber: "577",
  },
  {
    id: 31,
    isUser: false,
    fullName: "Ruperto Raffels",
    operationNumber: "649",
  },
  {
    id: 32,
    isUser: true,
    fullName: "Gun Macquire",
    operationNumber: "505",
  },
  {
    id: 33,
    isUser: false,
    fullName: "Joan Ciani",
    operationNumber: "766",
  },
  {
    id: 34,
    isUser: false,
    fullName: "Hunter Mayfield",
    operationNumber: "508",
  },
  {
    id: 35,
    isUser: false,
    fullName: "Brewer Scherme",
    operationNumber: "680",
  },
  {
    id: 36,
    isUser: false,
    fullName: "Erinn Hessel",
    operationNumber: "736",
  },
  {
    id: 37,
    isUser: true,
    fullName: "Leena Fissenden",
    operationNumber: "655",
  },
  {
    id: 38,
    isUser: true,
    fullName: "Aigneis Filon",
    operationNumber: "611",
  },
  {
    id: 39,
    isUser: true,
    fullName: "Dorolice Radleigh",
    operationNumber: "729",
  },
  {
    id: 40,
    isUser: false,
    fullName: "Ettie Eilles",
    operationNumber: "580",
  },
  {
    id: 41,
    isUser: false,
    fullName: "Fawne Anersen",
    operationNumber: "684",
  },
  {
    id: 42,
    isUser: false,
    fullName: "Allyn Rotter",
    operationNumber: "728",
  },
  {
    id: 43,
    isUser: true,
    fullName: "Ferdinande Vanin",
    operationNumber: "568",
  },
  {
    id: 44,
    isUser: false,
    fullName: "Jesse Coton",
    operationNumber: "790",
  },
  {
    id: 45,
    isUser: false,
    fullName: "Katuscha Sorey",
    operationNumber: "507",
  },
  {
    id: 46,
    isUser: true,
    fullName: "Matthew Iverson",
    operationNumber: "519",
  },
  {
    id: 47,
    isUser: false,
    fullName: "Ardeen De Robertis",
    operationNumber: "734",
  },
  {
    id: 48,
    isUser: true,
    fullName: "Kenyon McVittie",
    operationNumber: "664",
  },
  {
    id: 49,
    isUser: true,
    fullName: "Aigneis Anten",
    operationNumber: "540",
  },
  {
    id: 50,
    isUser: true,
    fullName: "Ryann Feldheim",
    operationNumber: "665",
  },
];

module.exports = {
  // these 3 are used to create the tasks lists in TasksCard - Dashboard view
  admin,
  support,
  users,
};
